services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    command: python3 app.py
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_APP=app.extensions:app
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    depends_on:
      - db
