services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5b2e05cd8c3526e3
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - SECRET_KEY=itsasecret
      - FLASK_APP=app.extensions:app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:5b2e05cd8c3526e3@merkoyep-final-project-db.dev.merkoyep.me:5432/postgres
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    depends_on:
      - db
volumes:
  db_data:
