services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    command: python3 app.py
    environment:
      SECRET_KEY: 'itsasecret'
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    depends_on:
      - db
volumes:
  db_data:
